{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhouz.plugin",
    "module": "myPlugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "myPlugin-1.0.0.jar",
          "url": "myPlugin-1.0.0.jar",
          "size": 3165,
          "sha512": "0d1cf4594561d137a869be54972fc8be2a7d258868d7cb645b378c6399d28c17750e633e4840072a7006b50ddf99e544d85ddc255bc73b7829fd1ee65e2a2016",
          "sha256": "90c3cc8b854dcb81af168e75dda32b969e2dcf3e40fc2986def067471aec3b8b",
          "sha1": "492ec9e4bf68de6c10b7be419fcda7319f7f96e1",
          "md5": "e8139206e1a1021dcb868fab9d1b6b17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "myPlugin-1.0.0.jar",
          "url": "myPlugin-1.0.0.jar",
          "size": 3165,
          "sha512": "0d1cf4594561d137a869be54972fc8be2a7d258868d7cb645b378c6399d28c17750e633e4840072a7006b50ddf99e544d85ddc255bc73b7829fd1ee65e2a2016",
          "sha256": "90c3cc8b854dcb81af168e75dda32b969e2dcf3e40fc2986def067471aec3b8b",
          "sha1": "492ec9e4bf68de6c10b7be419fcda7319f7f96e1",
          "md5": "e8139206e1a1021dcb868fab9d1b6b17"
        }
      ]
    }
  ]
}
